options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker Image with build-time secrets
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/healthtrack-ai',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=$(NEXT_PUBLIC_FIREBASE_API_KEY)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(NEXT_PUBLIC_FIREBASE_PROJECT_ID)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=$(NEXT_PUBLIC_FIREBASE_APP_ID)',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID)',
        '.'
      ]
    secretEnv:
      - NEXT_PUBLIC_FIREBASE_API_KEY
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_FIREBASE_APP_ID
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

  # Step 2: Deploy to Cloud Run with runtime secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args:
      [
        'run', 'deploy', 'healthtrack-ai',
        '--image', 'gcr.io/$PROJECT_ID/healthtrack-ai',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'NEXT_PUBLIC_FIREBASE_API_KEY=$(NEXT_PUBLIC_FIREBASE_API_KEY),\
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN),\
        NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(NEXT_PUBLIC_FIREBASE_PROJECT_ID),\
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET),\
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID),\
        NEXT_PUBLIC_FIREBASE_APP_ID=$(NEXT_PUBLIC_FIREBASE_APP_ID),\
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID),\
        GEMINI_API_KEY=$(GEMINI_API_KEY),\
        GOOGLE_API_KEY=$(GOOGLE_API_KEY),\
        MONGODB_URI=$(MONGODB_URI),\
        MONGODBPW=$(MONGODBPW),\
        ATLAS_VECTOR_SEARCH_INDEX_NAME=$(ATLAS_VECTOR_SEARCH_INDEX_NAME),\
        GCLOUD_PROJECT=$(GCLOUD_PROJECT),\
        VERTEX_AI_ENDPOINT_HOST=$(VERTEX_AI_ENDPOINT_HOST),\
        VERTEX_AI_PROJECT_ID_FOR_ENDPOINT=$(VERTEX_AI_PROJECT_ID_FOR_ENDPOINT),\
        VERTEX_AI_LOCATION_FOR_ENDPOINT=$(VERTEX_AI_LOCATION_FOR_ENDPOINT),\
        VERTEX_AI_ENDPOINT_ID_FOR_ENDPOINT=$(VERTEX_AI_ENDPOINT_ID_FOR_ENDPOINT)'
      ]
    secretEnv:
      - NEXT_PUBLIC_FIREBASE_API_KEY
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_FIREBASE_APP_ID
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      - GEMINI_API_KEY
      - GOOGLE_API_KEY
      - MONGODB_URI
      - MONGODBPW
      - ATLAS_VECTOR_SEARCH_INDEX_NAME
      - GCLOUD_PROJECT
      - VERTEX_AI_ENDPOINT_HOST
      - VERTEX_AI_PROJECT_ID_FOR_ENDPOINT
      - VERTEX_AI_LOCATION_FOR_ENDPOINT
      - VERTEX_AI_ENDPOINT_ID_FOR_ENDPOINT

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: NEXT_PUBLIC_FIREBASE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_APP_ID
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_API_KEY/versions/latest
      env: GOOGLE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
      env: MONGODB_URI
    - versionName: projects/$PROJECT_ID/secrets/MONGODBPW/versions/latest
      env: MONGODBPW
    - versionName: projects/$PROJECT_ID/secrets/ATLAS_VECTOR_SEARCH_INDEX_NAME/versions/latest
      env: ATLAS_VECTOR_SEARCH_INDEX_NAME
    - versionName: projects/$PROJECT_ID/secrets/GCLOUD_PROJECT/versions/latest
      env: GCLOUD_PROJECT
    - versionName: projects/$PROJECT_ID/secrets/VERTEX_AI_ENDPOINT_HOST/versions/latest
      env: VERTEX_AI_ENDPOINT_HOST
    - versionName: projects/$PROJECT_ID/secrets/VERTEX_AI_PROJECT_ID_FOR_ENDPOINT/versions/latest
      env: VERTEX_AI_PROJECT_ID_FOR_ENDPOINT
    - versionName: projects/$PROJECT_ID/secrets/VERTEX_AI_LOCATION_FOR_ENDPOINT/versions/latest
      env: VERTEX_AI_LOCATION_FOR_ENDPOINT
    - versionName: projects/$PROJECT_ID/secrets/VERTEX_AI_ENDPOINT_ID_FOR_ENDPOINT/versions/latest
      env: VERTEX_AI_ENDPOINT_ID_FOR_ENDPOINT
